# Training configuration for Sitching infomration prediction model 
# (part II of NeuralTailor)

experiment:
  project_name: Garments-Reconstruction
  run_name: NeuralTailor-Stitch-Model

# ----- Dataset-related properties -----
data_config:
  class: GarmentStitchPairsDataset  

  data_folders:
    - dress_sleeveless_2550
    - jumpsuit_sleeveless_2000
    - skirt_8_panels_1000
    - wb_pants_straight_1500
    - skirt_2_panels_1200
    - jacket_2200
    - tee_sleeveless_1800
    - wb_dress_sleeveless_2600
    - jacket_hood_2700
    - pants_straight_sides_1000
    - tee_2300
    - skirt_4_panels_1600

  old_experiment:
    project_name: Garments-Reconstruction
    run_name: Filt-Att-Condenced-Retry
    run_id: 25g4d6si
    stats: False   # Use data stats from previous training run in this one
    predictions: True  # use predictions of the previously trained model to train this one
                       # Training on shape predictions gives more robust stitch model
    
  use_old_exp_predictions: True    # use predictions of the previously trained model to train this one

  stitched_edge_pairs_num: 200
  non_stitched_edge_pairs_num: 200
  shuffle_pairs: True
  shuffle_pairs_order': True

  filter_by_params: ./nn/data_configs/param_filter.json

data_split:
  valid_per_type: 100
  test_per_type: 100
  random_seed: 10
  type: count
  # NOTE addining 'filename' property to the split will force the data 
  # to be loaded from that list, instead of being randomly generated
  filename: ./wandb/data_split.json


# ----- Network Architecture --------
NN:
  model: StitchOnEdge3DPairs
  stitch_hidden_size: 200
  stitch_mlp_n_layers: 3

  # ----- Losses ----
  loss:
    loss_components:  [edge_pair_class] 
    quality_components:  [edge_pair_class, edge_pair_stitch_recall] 


# ------- Trainer -----
trainer: 
  batch_size: 30   # For stitch experiments it corresponds to number of garment examples in a batch.
                   # Number of edge pairs in a batch would be (batch_size x (stitched_edge_pairs_num + non_stitched_edge_pairs_num))
  devices: [cuda:0]
  epochs: 350
  random_seed: 10
  learning_rate: 0.002
  optimizer: Adam
  weight_decay: 0
  lr_scheduling: 
    mode: 1cyclic
  early_stopping:
    window: 0.0001
    patience: 50
  with_visualization: False  # don't have good visualization for stitches anyway